name: Continuous Facebook Live Stream with Watermark and Resilience

on:
  workflow_dispatch:  # التشغيل اليدوي
  push:
    branches:
      - main  # يتم تشغيله عند دفع التغييرات على الفرع الرئيسي

jobs:
  stream:
    runs-on: ubuntu-latest  # البيئة المستخدمة للبث
    timeout-minutes: 1440  # يمكن تحديد المدة الزمنية حسب الحاجة (في هذا الحال 24 ساعة)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # تحقق من المستودع

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install ffmpeg -y  # تثبيت FFmpeg

      - name: Verify Ownership and Rights
        run: |
          OWNER_EMAIL="imadmaskali22@gmail.com"  # البريد الإلكتروني للمالك
          CURRENT_USER_EMAIL=$(git config --get user.email)
          if [ "$CURRENT_USER_EMAIL" != "$OWNER_EMAIL" ]; then
            echo "أنت لست المالك المصرح له! البث لن يبدأ."
            exit 1
          fi
          echo "المالك معتمد، بدء البث..."

      - name: Add Watermark and Start Stream
        run: |
          STREAM_KEY="FB-122166221492260989-0-AbyDiyB_Nr94DEcp"
          M3U8_URL="https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8"  # رابط m3u8 للبث
          RTMP_URL="rtmps://live-api-s.facebook.com:443/rtmp/${STREAM_KEY}"
          
          # بدء البث مع إضافة العلامة المائية (watermark)
          retry_count=0
          max_retries=5
          while [ $retry_count -lt $max_retries ]; do
            ffmpeg -re -i "${M3U8_URL}" -filter_complex "[0:v]drawtext=text='IMADTV.COM':fontcolor=white:fontsize=40:x=10:y=10" \
            -c:v libx264 -preset fast -b:v 1500k -c:a aac -ar 44100 -b:a 128k -f flv "${RTMP_URL}"
            if [ $? -eq 0 ]; then
              echo "البث بدأ بنجاح!"
              break
            else
              echo "فشل البث، إعادة المحاولة بعد 10 ثواني..."
              sleep 10
              retry_count=$((retry_count + 1))
            fi
          done

          if [ $retry_count -eq $max_retries ]; then
            echo "فشل البث بعد $max_retries محاولات."
            exit 1
          fi

      - name: Restart Action on Failure (Auto Restart)
        if: failure()  # إذا فشل البث أو انقطع
        run: |
          echo "إعادة تشغيل البث تلقائيًا..."
          curl -X POST https://api.github.com/repos/${{ github.repository }}/actions/workflows/facebook_live_stream.yml/dispatches \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"ref":"main"}'  # إرسال طلب إعادة تشغيل GitHub Action
